CREATE TABLE dungeon_template
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255) NOT NULL,
    description       VARCHAR(512),
    tier              INTEGER      NOT NULL,
    entry_cost_minor  BIGINT       NOT NULL DEFAULT 0,
    room_count        INTEGER      NOT NULL
);

CREATE TABLE dungeon_room_template
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dungeon_template_id INTEGER      NOT NULL REFERENCES dungeon_template (id),
    room_index          INTEGER      NOT NULL,
    room_type           VARCHAR(32)  NOT NULL,
    enemy_template_id   VARCHAR(64),
    loot_item_id        INTEGER REFERENCES item (id),
    loot_quantity       INTEGER      NOT NULL DEFAULT 0,
    loot_coins_minor    BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_dungeon_room UNIQUE (dungeon_template_id, room_index)
);

CREATE TABLE dungeon_run
(
    id                   UUID         NOT NULL PRIMARY KEY,
    user_id              UUID         NOT NULL,
    dungeon_template_id  INTEGER      NOT NULL REFERENCES dungeon_template (id),
    status               VARCHAR(32)  NOT NULL,
    current_room_index   INTEGER      NOT NULL DEFAULT 0,
    rng_seed             BIGINT       NOT NULL,
    current_fight_id     VARCHAR(64),
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_dungeon_run_user_id ON dungeon_run (user_id);

CREATE TABLE dungeon_run_loot
(
    id               BIGSERIAL PRIMARY KEY,
    dungeon_run_id   UUID    NOT NULL REFERENCES dungeon_run (id) ON DELETE CASCADE,
    item_id          INTEGER REFERENCES item (id),
    quantity         INTEGER NOT NULL DEFAULT 0,
    coins_minor      BIGINT  NOT NULL DEFAULT 0
);

INSERT INTO dungeon_template (id, name, description, tier, entry_cost_minor, room_count)
VALUES (1, 'Coral Caves', 'Starter dungeon with chest and battle rooms.', 1, 0, 3)
ON CONFLICT (id) DO NOTHING;

INSERT INTO dungeon_room_template (
    dungeon_template_id, room_index, room_type,
    enemy_template_id, loot_item_id, loot_quantity, loot_coins_minor
)
VALUES
    (1, 0, 'CHEST', NULL, 1, 1, 25),
    (1, 1, 'BATTLE', 'mob_coral_guard', NULL, 0, 50),
    (1, 2, 'BOSS', 'mob_coral_king', 5, 1, 100)
ON CONFLICT (dungeon_template_id, room_index) DO NOTHING;
