ALTER TABLE item
    ADD COLUMN crit_chance INT NOT NULL DEFAULT 0,
    ADD COLUMN crit_damage INT NOT NULL DEFAULT 0,
    ADD COLUMN accuracy INT NOT NULL DEFAULT 0,
    ADD COLUMN evasion INT NOT NULL DEFAULT 0,
    ADD COLUMN tenacity INT NOT NULL DEFAULT 0,
    ADD COLUMN status_power INT NOT NULL DEFAULT 0;
