CREATE TABLE action_idempotency
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         UUID                                    NOT NULL,
    action_type     VARCHAR(64)                             NOT NULL,
    idempotency_key VARCHAR(128)                            NOT NULL,
    status          VARCHAR(16)                             NOT NULL,
    response_json   OID,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_action_idempotency PRIMARY KEY (id)
);

CREATE TABLE octopus
(
    id                INTEGER      NOT NULL,
    name              VARCHAR(255) NOT NULL,
    element_type      VARCHAR(255) NOT NULL,
    tier              INTEGER      NOT NULL,
    attack_stat       INTEGER      NOT NULL,
    magic_power_stat  INTEGER      NOT NULL,
    armor_stat        INTEGER      NOT NULL,
    magic_resist_stat INTEGER      NOT NULL,
    speed_stat        INTEGER      NOT NULL,
    CONSTRAINT pk_octopus PRIMARY KEY (id)
);

CREATE TABLE user_octopus_stash
(
    user_id    UUID    NOT NULL,
    octopus_id INTEGER NOT NULL,
    quantity   INTEGER NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_user_octopus_stash PRIMARY KEY (user_id, octopus_id)
);

ALTER TABLE action_idempotency
    ADD CONSTRAINT uq_action_idempotency UNIQUE (user_id, action_type, idempotency_key);