CREATE TABLE item
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                             NOT NULL,
    description VARCHAR(255),
    slot        VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE octopus_skill
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                             NOT NULL,
    description  VARCHAR(255),
    element_type VARCHAR(32)                              NOT NULL,
    cooldown_ms  INTEGER                                  NOT NULL,
    mana_cost    INTEGER                                  NOT NULL,
    CONSTRAINT pk_octopus_skill PRIMARY KEY (id)
);

CREATE TABLE octopus_skill_effect
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    skill_id          INTEGER                                 NOT NULL,
    effect_type       VARCHAR(32)                             NOT NULL,
    element_type      VARCHAR(32)                             NOT NULL,
    base_value        INTEGER                                 NOT NULL,
    scaling_stat      VARCHAR(32),
    scaling_ratio_bps INTEGER,
    duration_ms       INTEGER,
    tick_ms           INTEGER,
    stacking_rule     VARCHAR(32),
    CONSTRAINT pk_octopus_skill_effect PRIMARY KEY (id)
);

CREATE TABLE user_octopus
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           UUID                                     NOT NULL,
    level             INTEGER                                  NOT NULL,
    exp               INTEGER                                  NOT NULL,
    attack_stat       INTEGER                                  NOT NULL,
    magic_power_stat  INTEGER                                  NOT NULL,
    armor_stat        INTEGER                                  NOT NULL,
    magic_resist_stat INTEGER                                  NOT NULL,
    speed_stat        INTEGER                                  NOT NULL,
    base_octopus      INTEGER                                  NOT NULL,
    CONSTRAINT pk_user_octopus PRIMARY KEY (id)
);

CREATE TABLE user_octopus_equipment
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_octopus_id INTEGER                                  NOT NULL,
    item_id         INTEGER                                  NOT NULL,
    slot            VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_user_octopus_equipment PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IX_pk_user_octopus_stash ON user_octopus_stash (user_id, octopus_id);

ALTER TABLE octopus_skill_effect
    ADD CONSTRAINT FK_OCTOPUS_SKILL_EFFECT_ON_SKILL FOREIGN KEY (skill_id) REFERENCES octopus_skill (id);

ALTER TABLE user_octopus_equipment
    ADD CONSTRAINT FK_USER_OCTOPUS_EQUIPMENT_ON_ITEM FOREIGN KEY (item_id) REFERENCES item (id);

ALTER TABLE user_octopus_equipment
    ADD CONSTRAINT FK_USER_OCTOPUS_EQUIPMENT_ON_USER_OCTOPUS FOREIGN KEY (user_octopus_id) REFERENCES user_octopus (id);

ALTER TABLE user_octopus
    ADD CONSTRAINT FK_USER_OCTOPUS_ON_BASE_OCTOPUS FOREIGN KEY (base_octopus) REFERENCES octopus (id);
