CREATE TABLE user_item_stack
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    UUID                                    NOT NULL,
    item_id    INTEGER                                 NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_user_item_stack PRIMARY KEY (id)
);

CREATE TABLE user_octopus_skill_slot
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_octopus_id INTEGER                                 NOT NULL,
    slot_index      INTEGER                                 NOT NULL,
    skill_id        INTEGER,
    CONSTRAINT pk_user_octopus_skill_slot PRIMARY KEY (id)
);

CREATE TABLE user_skill_unlock
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     UUID                                    NOT NULL,
    skill_id    INTEGER                                 NOT NULL,
    unlocked_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_user_skill_unlock PRIMARY KEY (id)
);

ALTER TABLE user_item_stack
    ADD CONSTRAINT uq_user_item_stack UNIQUE (user_id, item_id);

ALTER TABLE user_octopus_skill_slot
    ADD CONSTRAINT uq_user_octopus_skill_slot UNIQUE (user_octopus_id, slot_index);

ALTER TABLE user_skill_unlock
    ADD CONSTRAINT uq_user_skill_unlock UNIQUE (user_id, skill_id);

ALTER TABLE user_item_stack
    ADD CONSTRAINT FK_USER_ITEM_STACK_ON_ITEM FOREIGN KEY (item_id) REFERENCES item (id);

ALTER TABLE user_octopus_skill_slot
    ADD CONSTRAINT FK_USER_OCTOPUS_SKILL_SLOT_ON_SKILL FOREIGN KEY (skill_id) REFERENCES octopus_skill (id);

ALTER TABLE user_octopus_skill_slot
    ADD CONSTRAINT FK_USER_OCTOPUS_SKILL_SLOT_ON_USER_OCTOPUS FOREIGN KEY (user_octopus_id) REFERENCES user_octopus (id);

ALTER TABLE user_skill_unlock
    ADD CONSTRAINT FK_USER_SKILL_UNLOCK_ON_SKILL FOREIGN KEY (skill_id) REFERENCES octopus_skill (id);