services:
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  twitch_service:
    image: ghcr.io/illcersei/twitch-service:main
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8002:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/twitch_monitor
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./logs/twitch:/app/logs

  pokeapi:
    image: pokeapi/pokeapi:master
    container_name: pokeapi
    profiles:
      - pokeapi
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8088:80"
    environment:
      POSTGRES_DB: ${POKEAPI_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      REDIS_CONNECTION_STRING: redis://redis:${SPRING_DATA_REDIS_PORT}/0
    volumes:
      - ./pokeapi-data/data/v2/csv:/code/data/v2/csv:ro
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data: