global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "auth-service"
    metrics_path: /actuator/prometheus
    basic_auth:
      username: prometheus
      password: strong_password
    static_configs:
      - targets:
          - "host.docker.internal:9001"
        labels:
          env: "prod"
          project: "my-project"

  - job_name: "twitch-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "host.docker.internal:9002"
        labels:
          env: "prod"
          project: "my-project"

  - job_name: "test-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "host.docker.internal:9003"
        labels:
          env: "prod"
          project: "my-project"

  - job_name: "profile-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "host.docker.internal:9004"
        labels:
          env: "prod"
          project: "my-project"

  - job_name: "wallet-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "host.docker.internal:9005"
        labels:
          env: "prod"
          project: "my-project"

  - job_name: "pokemon-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "host.docker.internal:9006"
        labels:
          env: "prod"
          project: "my-project"

  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "host.docker.internal:9100"
        labels:
          env: "prod"
          project: "my-project"

  - job_name: "cadvisor"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:9888"
        labels:
          env: "prod"
          project: "my-project"

  - job_name: "prometheus"
    static_configs:
      - targets:
          - "prometheus:9090"