spring:
  config:
    import: optional:file:.env.local[.properties]
  application:
    name: auth

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/auth_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mvc:
    servlet:
      path: /api/v1/auth

  jackson:
    deserialization:
      fail-on-unknown-properties: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

  kafka:
    bootstrap-servers: localhost:${SPRING_KAFKA_PORT}
    consumer:
      group-id: auth-consumer-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      missing-topics-fatal: false
    template:
      default-topic: user-registration

management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

metrics:
  username: ${METRICS_USERNAME}
  password: ${METRICS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

logging:
  level:
    org.springframework: info
    org.hibernate.SQL: info
    cersei.auth: info
  file:
    name: logs/auth.log

server:
  port: 8001
