ALTER TABLE games ALTER COLUMN game_id TYPE BIGINT;
ALTER TABLE games ALTER COLUMN game_id DROP DEFAULT;

ALTER TABLE viewer ALTER COLUMN id TYPE BIGINT;
ALTER TABLE viewer ALTER COLUMN id DROP DEFAULT;
ALTER TABLE viewer ALTER COLUMN game_id TYPE BIGINT;
ALTER TABLE viewer ALTER COLUMN game_id DROP DEFAULT;
